plugins {
    id 'java-gradle-plugin'
    id 'groovy'
}

group = 'kasuga.build'
version = '1.0.0'

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation localGroovy()
    implementation gradleApi()
    implementation("com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:9.0.2")
    testImplementation gradleTestKit()
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

gradlePlugin {
    plugins {
        kasugaBuilder {
            id = 'builder.kasuga.generator'
            implementationClass = 'builder.kasuga.KasugaGeneratorPlugin'
        }
        kasugaMonorepo {
            id = 'builder.kasuga.monorepo'
            implementationClass = 'builder.kasuga.KasugaMonorepoPlugin'
        }
        kasugaResourceCompiler {
            id = 'builder.kasuga.resource-compiler'
            implementationClass = 'builder.kasuga.KasugaResourceCompilerPlugin'
        }
        kasugaShader {
            id = 'builder.kasuga.shader'
            implementationClass = 'builder.kasuga.KasugaShaderPlugin'
        }
    }
}
